### ISSUE TITLE
Graph to visualize relationship between entities

### ISSUE THREAD

**Issue by lydavid** [lydavid/MusicSearch#1003]
## Details
- learn about force-directed graph: https://github.com/d3/d3-force
  - interactive examples: https://observablehq.com/@ben-tanen/a-tutorial-to-using-d3-force-from-someone-who-just-learned-ho
  - in-depth explanation with examples: https://www.d3indepth.com/force-layout/
  - Kotlin javafx implementation: https://github.com/hudsonb/kubed
  - Java Android View: https://github.com/kai0masanari/Forcelayout
  - JavaFX has better performance than Canvas once circular nodes reaches 30000: https://dev.to/gz_k/jetpack-compose-desktop-rendering-performances-4992
  - [data2viz](https://github.com/data2viz/data2viz) is a Kotlin implementation of d3. Their sim uses JavaFX. Here are [some usages](https://github.com/search?q=d2v-viz+NOT+is%3Afork&type=code) filtering out forks.
  - [collage](https://github.com/pt2121/collage) is a [data2viz](https://data2viz.io) port/wrapper for Jetpack Compose. They have a sample app that uses their wrapper module [collage](https://github.com/pt2121/collage/blob/main/collage/build.gradle)
  - Obsidian's graph view: it does have decay where it stops moving unless I drag a node around
- learn about Canvas: https://developer.android.com/develop/ui/compose/graphics/draw/overview
  - when to use drawWithCache?
- [ ] Performance bottleneck is with rendering engine. So, add option to turn off animation to improve performance for lower end phones. All the calculations will be complete, then we render the final result.
- [x] a more useful usecase would be to show artists that have collaborated with this artist
  - [x] an artist has collaborated with another artist if they are both on the artist credits for a recording
  - [x] do not display all recordings (can already see under Recordings tab). Display recordings where there are multiple artist credits
- ~~A simple starter graph may be to show all relationships that points to this current entity (the incoming edges). We don't need to show all relationships from a given entity because it's already shown in the Relationships tab.~~ We already have this information because relationships are two-way
- [ ] #1024 

## Make nodes clickable
When I zoom, clicking is no longer accurate
When I pan, there's no problem as I'm handling offset

## Strength based on number of links
https://d3js.org/d3-force/link#link_strength

## The starting position of nodes matters because the simulation only lasts so long
and if we make it last forever, it will often tangle up

**Comment by lydavid** [comment]
## What should be written in Compose?
- nodes and positions should be passed down

## What should be written in non-Compose Kotlin?

## What is the most simple Canvas API for our use case?
Draw a circle with some radius at some position on the canvas

## How do I animate it?

**Comment by lydavid** [comment]
## Cannot run on Desktop

Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
	at javafx.animation.AnimationTimer.<init>(AnimationTimer.java:74)
	at io.data2viz.timer.JavaFxTimer.<init>(TimerJfx.kt:64)
	at io.data2viz.timer.TimerJfxKt$fxTimer$2.invoke(TimerJfx.kt:56)
	at io.data2viz.timer.TimerJfxKt$fxTimer$2.invoke(TimerJfx.kt:56)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.data2viz.timer.TimerJfxKt.getFxTimer(TimerJfx.kt:56)
	at io.data2viz.timer.TimerJfxKt.callInNextFrame(TimerJfx.kt:59)
	at io.data2viz.timer.TimerKt.now(Timer.kt:241)
	at io.data2viz.timer.TimerKt.timer$default(Timer.kt:110)
	at io.data2viz.force.ForceSimulation.<init>(ForceSimulation.kt:87)
	at io.data2viz.force.ForceKt.forceSimulation(Force.kt:23)
	at ly.david.musicsearch.shared.feature.graph.GraphSimulation.initialize(GraphSimulation.kt:58)
	at ly.david.musicsearch.shared.feature.graph.GraphPresenter$present$1.invokeSuspend(GraphPresenter.kt:45)

**Comment by lydavid** [comment]
runs on iOS

**Comment by lydavid** [comment]
pick better colors

https://www.colorhexa.com/ff225c
https://webaim.org/resources/contrastchecker/
